# Generated by Django 4.2.13 on 2024-06-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=100)),
                ('cus_email', models.EmailField(max_length=254)),
                ('cus_phone_number', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('number_of_people', models.IntegerField()),
                ('massage', models.TextField()),
            ],
        ),
    ]
