# Generated by Django 4.2.13 on 2024-06-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='tb_customer',
        ),
    ]
